### ISSUE TITLE
clipboard error "target STRING not available"

### ISSUE THREAD

**Issue by Valodim** [tversteeg/registers.nvim#39] opened 2021-09-03 17:00 UTC
First of all, thanks for this simple and useful nvim plugin! Super useful :+1: 

When I copy an image to the clipboard (e.g. my avatar while writing this issue on github), registers.nvim break outputting this error:

```
E5108: Error executing lua ...os/github.com/tversteeg/registers.nvim/lua/registers.lua:81: Vim:clipboard: provider returned invalid data
```

**Comment by tversteeg** [comment] 2021-09-08 14:48
Hi, thanks for the report. What OS are you using? I can't reproduce this myself running Debian.

**Comment by Valodim** [comment] 2021-09-08 20:02
I'm using NixOS, with neovim built from the 0.5.0 tag. Perhaps it's just an issue with neovim itself? The API call looks pretty innocent really on your side. Maybe it's worth catching the exception and simply considering the register empty if it fails?

**Comment by Valodim** [comment] 2021-09-08 20:11
going by [this comment](https://github.com/neovim/neovim/issues/2642#issuecomment-170271675), the issue might be something about neovim using `xsel` vs `xclip` as clipboard provider? Whatever the root cause, it seems the call can fail in unexpected ways on some neovims.

**Comment by tversteeg** [comment] 2021-09-13 08:43
Closing this issue because it doesn't seem to be related to this plugin.

**Closed by tversteeg** 2021-09-13 08:43 UTC
Labels: bug
