### ISSUE TITLE
Vim 0.8 Error E5113: Error while calling lua chunk 

### ISSUE THREAD

**Issue by clauseggers** [tversteeg/registers.nvim#71] opened 2022-10-02 12:20 UTC
### Please select which platform you are using.

Mac

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since the update to Neovim 0.8 I have been getting the following error:

```
Error detected while processing /Users/claus/.local/share/nvim/plugged/registers.nvim/plugin/registers.lua:
E5113: Error while calling lua chunk: vim/shared.lua:0: key found in more than one map: symbols
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'tbl_extend'
        ...l/share/nvim/plugged/registers.nvim/plugin/registers.lua:67: in main chunk
Press ENTER or type command to continue
```

A cursory search on E5113 indicates that this might be a Homebrew issue (I do have Neovim installed via Homebrew). Got any ideas?

**Comment by tversteeg** [comment] 2022-10-02 13:28
That's very odd, what exact version are you using?

**Comment by clauseggers** [comment] 2022-10-02 13:41
```
$ vi --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

**Comment by tversteeg** [comment] 2022-10-02 14:14
I installed the same version, but on Linux instead of Mac and I can't reproduce it:

```
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

It does look like a Mac specific issue, unfortunately I don't own a Mac so I can't help you with that..

**Comment by clauseggers** [comment] 2022-10-02 14:46
Disabling the `~/.local/share/nvim/plugged/registers.nvim/plugin/registers.lua` file (by renaming it) will let nvim open without the error message. The other way around does not work.

That done the keyboard commands are no longer working, save for the one I defined myself.

I’ll see what happens once the first fixes for 0.8 comes my way.

**Comment by clauseggers** [comment] 2022-10-08 12:25
I have just tried this in a Linux VM (OpenSUSE Tumbleweed), and I also get the exact same error there.
```
NVIM v0.8.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/src -I/usr/include -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by tversteeg** [comment] 2022-10-08 21:16
Interesting, is your init.lua or vimrc available by any chance? Maybe there's some collision with another setting or plugin.

**Comment by clauseggers** [comment] 2022-10-09 08:30
It is. https://gist.github.com/clauseggers/668fbf5a1a5c7fa8560df1d4e0b40c07

**Comment by fanxiao92** [comment] 2022-10-14 09:43
https://gist.github.com/clauseggers/668fbf5a1a5c7fa8560df1d4e0b40c07#file-init-vim-L380
check the registers.nvim version, the main branch is dont use  let g:registers_tab_symbol = "→".

**Comment by tversteeg** [comment] 2022-10-14 09:55
Should be fixed in the latest commit, this had to do with the migration message I wrote, @fanxiao92 is right, you should use the new format.

**Closed** 2022-10-14 09:54 UTC
Labels: bug

**Comment by clauseggers** [comment] 2022-10-14 09:56
Am I correct in understanding that the format of the new options are in the new Lua format that only works in Neovim? I’m a recent convert from old hat Vim, and as I understand it Neovim is now moving over to a number of Lua-formatted config files instead of the old viminit format?

**Comment by tversteeg** [comment] 2022-10-14 09:59
Mabye I should clarify this in the README, but you can also call Lua from inside Vimscript:

```vimscript
lua << EOF
local registers = require("registers")
registers.setup({})
EOF
```

**Comment by clauseggers** [comment] 2022-10-14 10:17
Thank you, I got it working. I will have convert my init to the new Lua system. This mixed format is not elegant.
